### ISSUE TITLE
实现盘点功能

### ISSUE THREAD

**Issue by nanbowen** [TinderTeam/Fuego#1]
实现盘点下发、验收、盘点表打印等功能

**Comment by tangjun114** [comment]
实现完成，请测试

**Comment by nanbowen** [comment]
Nice Job 请 @aether1989 验收关闭

**Comment by aether1989** [comment]
问题1：发送验收单的用户只能看到验收情况，不可更改！

**Comment by aether1989** [comment]
问题2：第一次上载验收测试表，流程可以走通，但是在油站确认完成后，上一级看到有两项已完成事项

**Comment by aether1989** [comment]
问题3：对同一张验收测试表第二次导入，（前一次操作已完成事项记录删除），出现异常，概率100%
在异常读取中，跟数据库组合主键有关（重装数据库OK）

**Comment by nanbowen** [comment]
关于 @aether1989 提出的3个问题的答复 :+1: 
问题1 此状态为需求确定，没有问题。
问题2 出现的原因为合并代码时的问题。现在已经解决
问题3 的出现原因： 同一张表如果出现手动指定编号固定资产，则会出现主键重复异常，这个我将对该异常进行捕获。

请验收关闭! :1234:
