### ISSUE TITLE
采购计划创建，重新填写功能有问题。

### ISSUE THREAD

**Issue by aether1989** [TinderTeam/Fuego#29]
创建采购计划，选定资产后进入到定制采购计划页面，重新填写功能缺失

**Comment by tangjun114** [comment]
导入异常 之后应该将该事务删除，1.0.23版本测试

**Comment by nanbowen** [comment]
@tangjun114  理解错误，该问题是，创建采购计划后，重新填写功能未实现，查询添加功能也未实现。

**Comment by tangjun114** [comment]
暂时屏蔽该功能，由后续需求 驱动

**Comment by nanbowen** [comment]
屏蔽之
