### ISSUE TITLE
资产验收可以简化功能

### ISSUE THREAD

**Issue by aether1989** [TinderTeam/Fuego#30]
1、验收是通过验收表导入的，所以导出的功能多余
2、返回功能是返回到初始验收页面，而取消则是返回到首页
个人认为取消则是用户重新操作，返回则返回上一页面（具备数据），首页可以在左侧一键进入，不需要在子功能页面增加

**Comment by nanbowen** [comment]
1.的确导出功能多余，如果已经实现则保留，若未实现则在数据手册中做一说明 @aether1989 
2.返回功能，建议按照 @aether1989 的建议，将所有模块的操作流程统一 @tangjun114 ，在下一个修正周期处理即可

请 @tangjun114  提意见。

**Comment by nanbowen** [comment]
1.导入未多余，因为进行了资产拆分 @aether1989

**Comment by tangjun114** [comment]
非问题 请确认关闭
