### ISSUE TITLE
基础数据导入——导入数据错误

### ISSUE THREAD

**Issue by nanbowen** [TinderTeam/Fuego#31]
导入数据数量全为6，原因：将行号误当做内容传入。
解决：
//Quantity  
                        cell = sheet.getCell(6,i);
                        numCell=(NumberCell) cell;

```
                    assets.setQuantity((int)numCell.getValue());
```

@aether1989  待测试(请在NanBowen -Brach 分支测试)

**Comment by aether1989** [comment]
OK，已改为1，外网登陆系统
