### ISSUE TITLE
盘点填报——备注信息没有导入

### ISSUE THREAD

**Issue by nanbowen** [TinderTeam/Fuego#32]
现象：导出后备注栏中没有信息。
分析可能是form没传进来，请 @tangjun114 定位解决。

**Comment by tangjun114** [comment]
已经修改，问题有两个，1数据库创建脚本没有改，2 读数据库没有将note读出来

请测试回归

![qq20131112020449](https://f.cloud.github.com/assets/5470558/1515081/831450e6-4afc-11e3-96d7-646b5523ab54.png)

**Comment by nanbowen** [comment]
请操哥测试

**Comment by nanbowen** [comment]
已经测试完毕
