### ISSUE TITLE
资产惠州，流转到财务负责人拒绝后依然在负责人待办事项中未退回。

### ISSUE THREAD

**Issue by nanbowen** [TinderTeam/Fuego#36]

**Comment by tangjun114** [comment]
资产回收，没有实现返回的接口，现在已经OK

**Comment by nanbowen** [comment]
请加入更正后的版本号，方便 @aether1989 进行测试

**Comment by tangjun114** [comment]
1.0.23 版本测试

**Comment by nanbowen** [comment]
![image](https://f.cloud.github.com/assets/5795691/1532333/70afcef6-4c75-11e3-97ee-dd38043b3724.png)
 经过测试，拒绝后未出现事件
