### ISSUE TITLE
事务被拒绝后，希望现实被拒绝，或类似说明

### ISSUE THREAD

**Issue by nanbowen** [TinderTeam/Fuego#38]

**Comment by tangjun114** [comment]
在1.0.23 中测试，
以前状态时绑定 step的
现在 在数据库中，增加了一个字段用于存储状态，然后在每次调用 backward方法的时候 更新状态为审批未通过
![qq20131113011326](https://f.cloud.github.com/assets/5470558/1523942/5ae5b692-4bbe-11e3-8d8c-8a9e2dd1cc3a.png)

**Comment by nanbowen** [comment]
![image](https://f.cloud.github.com/assets/5795691/1532305/021e7d84-4c75-11e3-8eb9-502a121a7e7c.png)
@aether1989  帮你验收通过
