### ISSUE TITLE
资产台账油站查询的限制。

### ISSUE THREAD

**Issue by nanbowen** [TinderTeam/Fuego#41]

**Comment by tangjun114** [comment]
修改查询条件，当用户为油站时，责任部门只显示该油站

![qq20131114010925](https://f.cloud.github.com/assets/5470558/1533511/81f3bcf2-4c86-11e3-84dd-289f3412d3f1.png)
![qq20131114011013](https://f.cloud.github.com/assets/5470558/1533518/a2abff90-4c86-11e3-9e54-ad6ed413582e.png)
