### ISSUE TITLE
基础数据导入问题

### ISSUE THREAD

**Issue by aether1989** [TinderTeam/Fuego#6]
1、新版软件20131031,导入基础数据出错，日期报错，
2、连续导入基础数据出问题，

**Comment by nanbowen** [comment]
1.因前期使用的Excel数据导入使用的模版和下载得到的模版不一致，所以导致串行，于是出现日期报错的问题。我在今天的优化中已经解决。
2.连续导入的问题，按照以前的设计是直接基础数据备份->清空->并重新导入。这个问题将继续保留。并转交Tangjun解决。
