### ISSUE TITLE
验收事务删除后，加油站权限的子验收事务依然存在且无法删除。

### ISSUE THREAD

**Issue by nanbowen** [TinderTeam/Fuego#67]
图中前两个事务已经删除，但在加油站的权限下依然显示并无法删除。
![image](https://f.cloud.github.com/assets/5795691/1608123/f6e5e6aa-54d0-11e3-84c8-6bfe76b61c0a.png)

**Comment by tangjun114** [comment]
我这边测试OK，请确认复现条件

**Comment by nanbowen** [comment]
新版本测试通过
