### ISSUE TITLE
创建资产采购计划需要增加取消功能

### ISSUE THREAD

**Issue by aether1989** [TinderTeam/Fuego#7]
因为我发现返回之后，应该是取消本次采购计划创建流程的，但是事实上在待办事项里看到还有残留？？

**Comment by nanbowen** [comment]
这个需要找一个机会整体测一下，因为我觉得我们在这个“取消”或者”返回“功能的定义上有比较大的问题。很模糊，请@tangjun114抽空处理。

**Comment by nanbowen** [comment]
此Issue后期再次提交，本次关闭
