### ISSUE TITLE
台账资产修改

### ISSUE THREAD

**Issue by aether1989** [TinderTeam/Fuego#8]
台账资产查询，点击修改，修改后点击提交，可以调到成功页面，但是数据库未作对应更新
换到旧版软件20131030 是OK的

**Comment by tangjun114** [comment]
我测试 没有问题，请说明 具体问题，是哪个字段的修改 没有生效

![km 5ae s i7ytiey mq](https://f.cloud.github.com/assets/5470558/1475798/008e4128-4641-11e3-8ca8-3d4815b39a35.jpg)

**Comment by tangjun114** [comment]
请测试回归
